name: 10_Resuable_Practice_Workflow
on:
    workflow_dispatch:
    push:
jobs:
    call_reusable_workflow:
        uses: ./.github/workflows/ReusableWorkflow.yml
        with:
            practice_input: "Hello from 10_Resuable_Practice_Workflow"