name: 11_Composite actions reuse
on: 
    workflow_dispatch:
    push:
jobs: 
    calling_actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: call actions
              uses: ./.github/actions/actions.yml


