name: 2_Multiple line commands, push event & expression and context object
on: push 
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print multiple line code
              run: |
                echo Print line one
                echo '${{toJson(github)}}' 