name: Using Actions in workflow and multiple jobs- in parallel
on: push
jobs: 
    test_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Print job success
              run: echo Test success!

    dev_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Print Dev Success
              run: echo Dev Success!