name: 4_Multiple jobs- in sequence & push event
on: push
jobs: 
    test_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Print job success
              run: echo Test success!

    dev_job:
      needs: test_job
      runs-on: ubuntu-latest
      steps: 
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Print Dev Success
              run: echo Dev Success!

    prod_job:
      needs: dev_job
      runs-on: ubuntu-latest
      steps: 
            - name: Checkout code Prod
              uses: actions/checkout@v4
            - name: Print Prod Success
              run: |
                echo Prod Success!
                echo "All jobs executed in sequence!"