name: 7_Environment Variables and Secrets
on: 
    workflow_dispatch:
    push:
jobs: 
    set_env_and_secret:
            runs-on: ubuntu-latest
            env:
                SAMPLE_ENV_VAR: "This is a sample environment variable"
            steps:
                - name: Checkout Code
                  uses: actions/checkout@v4
                - name: Print Environment Variable
                  run: | 
                    echo "Environment Variable: $SAMPLE_ENV_VAR"
                - name: Use Secret
                  run: |
                    echo 'Secret Value: ${{ secrets.SAMPLE_SECRET }}'
                - name: Default Environment Variable
                  run: |
                    echo "Home Directory: $HOME"
                    echo "Runner OS: $RUNNER_OS"
                    echo "GitHub Workspace: $GITHUB_WORKSPACE"
                    echo " GitHub Owner: $GITHUB_REPOSITORY_OWNER"