name: 8_Controlling workflow and job execution
on:
    workflow_dispatch:
    push:
jobs:
    practice-8:
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Run a script
              run: echo "This job runs only on workflow dispatch events."
            - name: Step that may fail
              continue-on-error: true
              run: |
                echo "This step will fail"
                exit 1
            - name: Final step
              if: failure()
              run: echo "This step runs regardless of previous step's success."